/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLucideBot: typeof import('~icons/lucide/bot')['default']
    IconLucideBug: typeof import('~icons/lucide/bug')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideClipboardCopy: typeof import('~icons/lucide/clipboard-copy')['default']
    IconLucideCode: typeof import('~icons/lucide/code')['default']
    IconLucideCopy: typeof import('~icons/lucide/copy')['default']
    IconLucideEye: typeof import('~icons/lucide/eye')['default']
    IconLucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    IconLucideFile: typeof import('~icons/lucide/file')['default']
    IconLucideLoaderCircle: typeof import('~icons/lucide/loader-circle')['default']
    IconLucideLock: typeof import('~icons/lucide/lock')['default']
    IconLucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    IconLucidePlay: typeof import('~icons/lucide/play')['default']
    IconLucideSend: typeof import('~icons/lucide/send')['default']
    IconLucideSidebar: typeof import('~icons/lucide/sidebar')['default']
    IconLucideSparkles: typeof import('~icons/lucide/sparkles')['default']
    IconLucideSquare: typeof import('~icons/lucide/square')['default']
    IconLucideTrash2: typeof import('~icons/lucide/trash2')['default']
    IconLucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
    IconLucideUnlock: typeof import('~icons/lucide/unlock')['default']
  }
}
