/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLucideALargeSmall: typeof import('~icons/lucide/a-large-small')['default']
    IconLucideAlertTriangle: typeof import('~icons/lucide/alert-triangle')['default']
    IconLucideAlignCenter: typeof import('~icons/lucide/align-center')['default']
    IconLucideAlignCenterHorizontal: typeof import('~icons/lucide/align-center-horizontal')['default']
    IconLucideAlignCenterVertical: typeof import('~icons/lucide/align-center-vertical')['default']
    IconLucideAlignEndHorizontal: typeof import('~icons/lucide/align-end-horizontal')['default']
    IconLucideAlignEndVertical: typeof import('~icons/lucide/align-end-vertical')['default']
    IconLucideAlignLeft: typeof import('~icons/lucide/align-left')['default']
    IconLucideAlignRight: typeof import('~icons/lucide/align-right')['default']
    IconLucideAlignStartHorizontal: typeof import('~icons/lucide/align-start-horizontal')['default']
    IconLucideAlignStartVertical: typeof import('~icons/lucide/align-start-vertical')['default']
    IconLucideArrowDown: typeof import('~icons/lucide/arrow-down')['default']
    IconLucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    IconLucideBaseline: typeof import('~icons/lucide/baseline')['default']
    IconLucideBlend: typeof import('~icons/lucide/blend')['default']
    IconLucideBold: typeof import('~icons/lucide/bold')['default']
    IconLucideBot: typeof import('~icons/lucide/bot')['default']
    IconLucideBug: typeof import('~icons/lucide/bug')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideClipboardCopy: typeof import('~icons/lucide/clipboard-copy')['default']
    IconLucideCode: typeof import('~icons/lucide/code')['default']
    IconLucideCopy: typeof import('~icons/lucide/copy')['default']
    IconLucideEye: typeof import('~icons/lucide/eye')['default']
    IconLucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    IconLucideFlipHorizontal2: typeof import('~icons/lucide/flip-horizontal2')['default']
    IconLucideFlipVertical2: typeof import('~icons/lucide/flip-vertical2')['default']
    IconLucideFolderPlus: typeof import('~icons/lucide/folder-plus')['default']
    IconLucideImage: typeof import('~icons/lucide/image')['default']
    IconLucideItalic: typeof import('~icons/lucide/italic')['default']
    IconLucideLayoutGrid: typeof import('~icons/lucide/layout-grid')['default']
    IconLucideLink: typeof import('~icons/lucide/link')['default']
    IconLucideLoaderCircle: typeof import('~icons/lucide/loader-circle')['default']
    IconLucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    IconLucideMinus: typeof import('~icons/lucide/minus')['default']
    IconLucidePlay: typeof import('~icons/lucide/play')['default']
    IconLucidePlus: typeof import('~icons/lucide/plus')['default']
    IconLucideRotateCw: typeof import('~icons/lucide/rotate-cw')['default']
    IconLucideRotateCwSquare: typeof import('~icons/lucide/rotate-cw-square')['default']
    IconLucideSearch: typeof import('~icons/lucide/search')['default']
    IconLucideSend: typeof import('~icons/lucide/send')['default']
    IconLucideSettings: typeof import('~icons/lucide/settings')['default']
    IconLucideSettings2: typeof import('~icons/lucide/settings2')['default']
    IconLucideSparkles: typeof import('~icons/lucide/sparkles')['default']
    IconLucideSquare: typeof import('~icons/lucide/square')['default']
    IconLucideSquareRoundCorner: typeof import('~icons/lucide/square-round-corner')['default']
    IconLucideStrikethrough: typeof import('~icons/lucide/strikethrough')['default']
    IconLucideTrash2: typeof import('~icons/lucide/trash2')['default']
    IconLucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
    IconLucideUnderline: typeof import('~icons/lucide/underline')['default']
    IconLucideUnlink: typeof import('~icons/lucide/unlink')['default']
    IconLucideWrapText: typeof import('~icons/lucide/wrap-text')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
  }
}
