#!/bin/bash

echo "=== GWT 생성 조건 확인 ==="
echo ""
echo "Neo4j Browser에서 다음 쿼리를 실행하세요:"
echo ""
echo "1. 전체 Command 개수:"
echo "   MATCH (cmd:Command) RETURN count(cmd) as total_commands;"
echo ""
echo "2. GWT 생성 조건에 부합하는 Command 개수 (Event가 있는 Command):"
echo "   MATCH (agg:Aggregate)-[:HAS_COMMAND]->(cmd:Command)"
echo "   OPTIONAL MATCH (cmd)-[:EMITS]->(evt:Event)"
echo "   WITH cmd, count(evt) as event_count"
echo "   WHERE event_count > 0"
echo "   RETURN count(DISTINCT cmd) as commands_with_events;"
echo ""
echo "3. 전체 Policy 개수:"
echo "   MATCH (pol:Policy) RETURN count(pol) as total_policies;"
echo ""
echo "4. GWT 생성 조건에 부합하는 Policy 개수 (Trigger Event가 있는 Policy):"
echo "   MATCH (evt:Event)-[:TRIGGERS]->(pol:Policy)"
echo "   RETURN count(DISTINCT pol) as policies_with_trigger_events;"
echo ""
echo "5. 실제 생성된 GWT 개수:"
echo "   MATCH (gwt:GWT) RETURN count(gwt) as total_gwt_created;"
echo ""
echo "6. 요약 (조건 부합 vs 실제 생성):"
echo "   MATCH (agg:Aggregate)-[:HAS_COMMAND]->(cmd:Command)"
echo "   OPTIONAL MATCH (cmd)-[:EMITS]->(evt:Event)"
echo "   OPTIONAL MATCH (cmd)-[:HAS_GWT]->(gwt_cmd:GWT)"
echo "   WITH cmd, count(DISTINCT evt) as event_count, gwt_cmd"
echo "   WHERE event_count > 0"
echo "   WITH count(DISTINCT cmd) as eligible_commands, count(DISTINCT gwt_cmd) as created_command_gwt"
echo "   MATCH (evt:Event)-[:TRIGGERS]->(pol:Policy)"
echo "   OPTIONAL MATCH (pol)-[:HAS_GWT]->(gwt_pol:GWT)"
echo "   WITH eligible_commands, created_command_gwt, count(DISTINCT pol) as eligible_policies, count(DISTINCT gwt_pol) as created_policy_gwt"
echo "   RETURN eligible_commands as 조건부합_Command개수,"
echo "          created_command_gwt as 생성된_Command_GWT개수,"
echo "          eligible_policies as 조건부합_Policy개수,"
echo "          created_policy_gwt as 생성된_Policy_GWT개수,"
echo "          eligible_commands + eligible_policies as 총_예상_GWT개수,"
echo "          created_command_gwt + created_policy_gwt as 총_생성된_GWT개수,"
echo "          (eligible_commands + eligible_policies) - (created_command_gwt + created_policy_gwt) as 누락된_GWT개수;"
echo ""
echo "7. Command별 GWT 생성 여부 상세:"
echo "   MATCH (cmd:Command)"
echo "   OPTIONAL MATCH (cmd)-[:HAS_GWT]->(gwt:GWT)"
echo "   OPTIONAL MATCH (agg:Aggregate)-[:HAS_COMMAND]->(cmd)"
echo "   OPTIONAL MATCH (cmd)-[:EMITS]->(evt:Event)"
echo "   RETURN cmd.name as command_name,"
echo "          CASE WHEN gwt IS NOT NULL THEN '생성됨' ELSE '미생성' END as gwt_status,"
echo "          count(DISTINCT evt) as event_count"
echo "   ORDER BY cmd.name;"
echo ""
echo "8. Policy별 GWT 생성 여부 상세:"
echo "   MATCH (pol:Policy)"
echo "   OPTIONAL MATCH (pol)-[:HAS_GWT]->(gwt:GWT)"
echo "   OPTIONAL MATCH (evt:Event)-[:TRIGGERS]->(pol)"
echo "   RETURN pol.name as policy_name,"
echo "          CASE WHEN gwt IS NOT NULL THEN '생성됨' ELSE '미생성' END as gwt_status,"
echo "          count(DISTINCT evt) as trigger_event_count"
echo "   ORDER BY pol.name;"
echo ""
echo "=== 전체 쿼리는 check_gwt_conditions.cypher 파일에 저장되어 있습니다 ==="
